// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9unXenFofoYMAyIYfiCQn1ld5qXlMVD8',
    appId: '1:580250337078:web:68f0e42608224b3e23fd97',
    messagingSenderId: '580250337078',
    projectId: 'ticketing-app-8b320',
    authDomain: 'ticketing-app-8b320.firebaseapp.com',
    storageBucket: 'ticketing-app-8b320.firebasestorage.app',
    measurementId: 'G-E6VXY7WFRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAj6D3zjlDmNUwpu_22cFi3EArRzm14EY',
    appId: '1:580250337078:android:072b7d8492e495d723fd97',
    messagingSenderId: '580250337078',
    projectId: 'ticketing-app-8b320',
    storageBucket: 'ticketing-app-8b320.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdd0OqXbCPh1oqG7HtHKf9ydf_PUE33is',
    appId: '1:580250337078:ios:aab7d7a7e3194e1323fd97',
    messagingSenderId: '580250337078',
    projectId: 'ticketing-app-8b320',
    storageBucket: 'ticketing-app-8b320.firebasestorage.app',
    iosBundleId: 'com.example.ticketApp',
  );
}
